"""add unique constraint to space name and site_id

Revision ID: 1b7ea1249a8b
Revises: 
Create Date: 2026-02-15 16:01:59.139906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7ea1249a8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_spaces_site_id_name', 'spaces', ['site_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_spaces_site_id_name', 'spaces', type_='unique')
    # ### end Alembic commands ###
