"""add due_date to payments table

Revision ID: 2bd5bca61857
Revises: 4fad460056f6
Create Date: 2026-02-16 09:50:09.153790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd5bca61857'
down_revision: Union[str, None] = '4fad460056f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'due_date')
    # ### end Alembic commands ###
