"""add unique constraint on space site_id+name

Revision ID: 4fad460056f6
Revises: 
Create Date: 2026-02-15 18:13:59.512172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fad460056f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_space_site_name', 'spaces', ['site_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_space_site_name', 'spaces', type_='unique')
    # ### end Alembic commands ###
